version: "3.8"

services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Map container port 80 to host
    depends_on:
      - api1
      - api2
    networks:
      - app-network
    container_name: "admin"
    # environment:
    #   - NODE_ENV=production
    env_file:
      - "./admin/.env"

  api1:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    networks:
      - app-network
    container_name: "api1"
    environment:
      - NODE_ENV=production
    env_file:
      - "./api/.env"

  api2:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    networks:
      - app-network
    container_name: "api2"
    environment:
      - NODE_ENV=production
    env_file:
      - "./api/.env"

networks:
  app-network:
    driver: bridge
